config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # READ ALL
  get 'tasks', to: 'tasks#index', as: 'index'
  # CREATE
  get 'tasks/new', to: 'tasks#new', as: 'create'
  post 'tasks', to: 'tasks#create'
  # UPDATE
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit'
  patch 'tasks/:id', to: 'tasks#update'
  # DELETE
  delete 'tasks/:id', to: 'tasks#destroy'
  # READ ONE
  get 'tasks/:id', to: 'tasks#show', as: 'task'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find, except: %i[index new create]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def find
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container my-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit <em><% @task.title%></em></h1>
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>
<hr>
<%= link_to "Back to list", index_path %>

app/views/tasks/index.html.erb
<h1>Your tasks:</h1>
<% @tasks.each do |task| %>
  <input type="checkbox" id="<%= task.title + task.id.to_s %>" name="<%= task.title + task.id.to_s %>" value="Task" <%= "checked" if task.completed %>>
  <label for="<%= task.title + task.id.to_s %>"> <%= link_to task.title, task_path(task) %> </label>
  <%= link_to "(Delete)", task_path(task.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %><br>
<% end %>
<hr>
<%= link_to "Add a new task", create_path %>

app/views/tasks/new.html.erb
<h1>Create a new task:</h1>
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>
<hr>
<%= link_to "Back to list", index_path %>

app/views/tasks/show.html.erb
<h1 style="display: inline-block;"> <%= @task.title %> </h1>
<%= link_to "Edit", edit_path %>
<p> <%= @task.details %> </p>
<input type="checkbox" id="<%= @task.title + @task.id.to_s %>" name="<%= @task.title + @task.id.to_s %>" value="Task" <%= "checked" if @task.completed %>>
<label for="<%= @task.title + @task.id.to_s %>"> <%= @task.completed ? "Completed" : "Not completed" %> </label><br><br>
<hr>
<%= link_to "Go back to list", index_path %>